### PR TITLE
fix: replace request with gaxios

### LINKED ISSUE #175: Chunks get lost when resuming upload with different data.
Pretty unfamiliar with this module, second pair of eyes would be good here!

It looks like we compare chunks to see if the user decided to resume the upload with different data
https://github.com/googleapis/gcs-resumable-upload/blob/master/src/index.ts#L347

If that happens, we put the chunk back in the `bufferStream`, buuut, once we restart we just toss that stream away
https://github.com/googleapis/gcs-resumable-upload/blob/master/src/index.ts#L294

I believe this would result in lost chunks, maybe?

### PR DESCRIPTION
**Pull request by stephenplusplus**
Fixes #175

## Blocked
- [x] https://github.com/JustinBeckwith/gaxios/pull/40
- [x] https://github.com/JustinBeckwith/gaxios/pull/42

## To Dos
- [x] Unit tests
- [x] System tests
- [x] Update readme with `response` event argument

This removes `request` and replaces it by calling the auth client's request method (which, as of now, uses gaxios).

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -283,37 +280,46 @@ export class Upload extends Pumpify {
...
+
+    this.pipe(requestStreamEmbeddedStream);
+
+    const reqOpts: GaxiosOptions = {
+      method: 'PUT',
+      url: this.uri,
+      headers: {
+        'Content-Range': 'bytes ' + this.offset + '-*/' + this.contentLength
+      },
+      body: requestStreamEmbeddedStream,
```
Comment (stephenplusplus) [inline src/index.ts]: This style of request complicates things. We have a stream that needs to be sent as the `body` of a request. So, normally, we would want to do:

```js
source.pipe(dest)
```

The equivalent with fetch is:

```js
request({ body: source }).then(resp => {
  resp.data.pipe(dest);
})
```

The `gcs-resumable-upload` class extends Pumpify, so we lose some simplicity by having to pipe ourselves into another stream, as opposed to *being* the stream.

File: package.json [hunk 2]
```diff
@@ -57,14 +56,15 @@
...
-    "gaxios": "^1.2.2",
     "codecov": "^3.0.4",
+    "gaxios": "^1.2.2",
     "gts": "^0.9.0",
     "intelli-espower-loader": "^1.0.1",
     "is-stream": "^1.1.0",
     "mocha": "^5.2.0",
     "mockery": "^2.1.0",
     "nock": "^10.0.0",
+    "node-fetch": "^2.3.0",
```
Comment (JustinBeckwith) [inline package.json]: It doesn't look like we use this, is it needed?

File: src/index.ts [hunk 3]
```diff
@@ -7,15 +7,12 @@
...
-import {GaxiosError, GaxiosOptions, GaxiosPromise} from 'gaxios';
+import {GaxiosError, GaxiosOptions, GaxiosPromise, GaxiosResponse} from 'gaxios';
 import {GoogleAuth, GoogleAuthOptions} from 'google-auth-library';
 import * as Pumpify from 'pumpify';
-import * as r from 'request';
-import {PassThrough} from 'stream';
+import {PassThrough, Transform} from 'stream';
 import * as streamEvents from 'stream-events';
 
-const request = r.defaults({json: true, pool: {maxSockets: Infinity}});
```
Comment (JustinBeckwith) [inline src/index.ts]: So I have no idea what `pool: {maxSockets: Infinity}` actually does, or if it's important.  Is this something we need to translate to gaxios speak?

File: src/index.ts [hunk 4]
```diff
@@ -283,37 +280,46 @@ export class Upload extends Pumpify {
...
+      this.emit('metadata', resp.data);
       this.deleteConfig();
       this.uncork();
     });
+
+    this.setPipeline(bufferStream, offsetStream, delayStream);
+
+    this.pipe(requestStreamEmbeddedStream);
+
+    const reqOpts: GaxiosOptions = {
```
Comment (JustinBeckwith) [inline src/index.ts]: I'm guessing you want to override `validateStatus` like the other requests:

`validateStatus: () => true`

File: src/index.ts [hunk 5]
```diff
@@ -431,26 +437,18 @@ export class Upload extends Pumpify {
...
-          await this.authClient.getRequestHeaders(reqOpts.url as string);
-      reqOpts.headers = Object.assign({}, reqOpts.headers, authHeaders);
-      const requestStream = request(reqOpts);
-      requestStream.on('error', this.destroy.bind(this));
-      requestStream.on('response', this.onResponse.bind(this));
-      requestStream.on('complete', (resp) => {
-        const body = resp.body;
-        if (body && body.error) this.destroy(body.error);
+
+      return this.authClient.request(reqOpts).then(res => {
```
Comment (JustinBeckwith) [inline src/index.ts]: since this is an async method, can you just:

```js
const res = await this.authClient.request(reqOpts);
this.onResponse(res);
return res;
```

File: system-test/kitchen.ts [hunk 6]
```diff
@@ -25,7 +25,7 @@ describe('end to end', () => {
         .on('error', done)
         .on('response',
             (resp) => {
-              uploadSucceeded = resp.statusCode === 200;
+              uploadSucceeded = resp.status === 200;
```
Comment (JustinBeckwith) [inline system-test/kitchen.ts]: So technically, is this an API breaking change?

Comment (stephenplusplus) [reply system-test/kitchen.ts]: Yeah, I believe it's safest to call it that. Adding a reminder to update the readme which tells users what `response` emits.

File: src/index.ts [hunk 7]
```diff
@@ -283,37 +280,46 @@ export class Upload extends Pumpify {
...
 
-      this.emit('metadata', resp.body);
+      this.emit('metadata', resp.data);
       this.deleteConfig();
       this.uncork();
     });
+
+    this.setPipeline(bufferStream, offsetStream, delayStream);
+
+    this.pipe(requestStreamEmbeddedStream);
```
Comment (callmehiphop) [inline src/index.ts]: Is this somehow different than

```js
this.setPipeline(bufferStream, offsetStream, delayStream, requestStreamEmbeddedStream);
```

File: src/index.ts (hunk 5 above)
Comment (callmehiphop) [inline src/index.ts]: I think you might want to do 

```js
return await this.authClient.request();
```

Otherwise I believe any request errors will not be caught by the `try/catch`

File: src/index.ts (hunk 7 above)
Comment (stephenplusplus) [reply src/index.ts]: Yeah, I tried many variations of that, and the request stream would never begin. This is a good one to clone and experiment with :)

File: src/index.ts [hunk 8]
```diff
@@ -431,26 +437,18 @@ export class Upload extends Pumpify {
     return res;
   }
 
-  private async getRequestStream(reqOpts: r.OptionsWithUrl):
-      Promise<r.Request> {
+  private async getRequestStream(reqOpts: GaxiosOptions):
```
Comment (callmehiphop) [inline src/index.ts]: Can we rename this? I was kind of confused when I noticed it no longer returns a stream.

File: src/index.ts (hunk 5 above)
Comment (stephenplusplus) [reply src/index.ts]: Would this work as well? https://github.com/googleapis/gcs-resumable-upload/pull/174#discussion_r252008963

File: src/index.ts (hunk 8 above)
Comment (stephenplusplus) [reply src/index.ts]: 👍 and I think there are some more things I can do to simplify it.

File: src/index.ts (hunk 5 above)
Comment (callmehiphop) [reply src/index.ts]: Yep! Missed that comment :)

File: src/index.ts (hunk 7 above)
Comment (callmehiphop) [reply src/index.ts]: Second question, since we're not setting this via `setPipeline`, does that mean we'll want to unpipe this stream in the event of a restart? I'm pretty new to this module, but it looks like previously `setPipeline` would essentially just kill off the old pump stream, where as now the upload stream will pipe into a new PassThrough stream every time `startUploading` is called.

Comment (stephenplusplus) [reply src/index.ts]: Great catch. I added a solution which I'll tag you in so you can see what you think.

File: package.json (hunk 2 above)
Comment (stephenplusplus) [reply package.json]: Nope, it's outta here!

File: src/index.ts [hunk 9]
```diff
@@ -283,37 +280,72 @@ export class Upload extends Pumpify {
...
+      // Allow the stream to continue naturally so the user's
+      // "finish" event fires.
       this.uncork();
     });
+
+    this.setPipeline(bufferStream, offsetStream, delayStream);
+
+    this.pipe(requestStreamEmbeddedStream);
+
+    this.once('restart', () => {
```
Comment (stephenplusplus) [inline src/index.ts]: @callmehiphop A new event is fired when `restart()` is called, which will let us unpipe the request stream.

File: src/index.ts [hunk 10]
```diff
@@ -283,37 +280,72 @@ export class Upload extends Pumpify {
...
-    const reqOpts = {
-      method: 'PUT',
-      url: this.uri!,
-      headers: {
-        'Content-Range': 'bytes ' + this.offset + '-*/' + this.contentLength
-      }
-    };
+    // The buffer stream allows us to keep chunks in memory
+    // until we are sure we can successfully resume the upload.
+    const bufferStream = this.bufferStream || new PassThrough();
```
Comment (stephenplusplus) [inline src/index.ts]: Fixes #175. Went with lazy-creating it instead of using the constructor, just to be consistent with our optimization path.

File: src/index.ts (hunk 4 above)
Comment (stephenplusplus) [reply src/index.ts]: Done!

File: src/index.ts (hunk 1 above)
Comment (callmehiphop) [reply src/index.ts]: Could we simplify this by creating a `createRequestStream` method (or something) in gaxios?

File: src/index.ts (hunk 3 above)
Comment (stephenplusplus) [reply src/index.ts]: `maxSockets` is the number of concurrent connections to the same host that are allowed. This was borrowed from our common code, which removes the limit that Node ships with by default. Node 6 and up set this to `Infinity` by default anyway, so I don't think we need this anymore.

File: src/index.ts (hunk 1 above)
Comment (stephenplusplus) [reply src/index.ts]: Issue opened: https://github.com/JustinBeckwith/gaxios/issues/39

**Comment by stephenplusplus** [comment]
@JustinBeckwith I think we're ready here!

File: package.json [hunk 11]
```diff
@@ -59,8 +59,8 @@
     "@types/request": "^2.47.0",
     "@types/through2": "^2.0.33",
     "assert-rejects": "^1.0.0",
-    "gaxios": "^1.2.2",
     "codecov": "^3.0.4",
+    "gaxios": "^1.6.0",
```
Comment (stephenplusplus) [inline package.json]: @JustinBeckwith gaxios is a devDependency here, but we require it in source code. Wat?

Comment (JustinBeckwith) [reply package.json]: That's really bad.  I would suggest against that 😆

**Comment by JustinBeckwith** [comment]
So, really annoying time question.  Can we get the code coverage up a bit?  Looks like we dropped.

File: package.json (hunk 11 above)
Comment (stephenplusplus) [reply package.json]: But that's how it is on master, I didn't add it! So, my thing is more like, what the heck? I'll change it as a dependency.

**Comment by stephenplusplus** [comment]
If there is a code coverage drop (is there?), this is the file that explains it: https://codecov.io/gh/googleapis/gcs-resumable-upload/pull/174/src/src/index.ts?before=src/index.ts. But, the only relevant line to the changes in this PR is:

image

Couldn't find what yellow means, but I have a test with and without `reqOpts.params` being defined.

So, I think this is just ready.
