### PR TITLE
fix: handle a `0` generation

### LINKED ISSUE #246: Failed to add ZERO generation number into the cache key
#### Environment details

  - `gcs-resumable-upload` version: 2.2.0

Failed to add generation number zero to the cache key due to following condition.

https://github.com/googleapis/gcs-resumable-upload/blob/450b9ea212eb7d0d1438a5496484d485ee4a0b5d/src/index.ts#L208

### PR DESCRIPTION
**Pull request by jiren**
Fixes #246 

- [x] Tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -205,7 +205,7 @@ export class Upload extends Pumpify {
     this.bucket = cfg.bucket;
 
     const cacheKeyElements = [cfg.bucket, cfg.file];
-    if (cfg.generation) {
+    if (!isNaN(cfg.generation!)) {
```
Comment (stephenplusplus) [inline src/index.ts]: NaN is actually pretty weird. Can you do "if (typeof cfg.generation === 'number') {"?

**Comment by stephenplusplus** [comment]
Woops. Thank you for fixing this!

File: src/index.ts (hunk 1 above)
Comment (jiren) [reply src/index.ts]: Updated condition.
