### PR TITLE
fix: typecast metadata.size from string to number

### LINKED ISSUE #221: metadata.size returned by upload string and not number
Note the necessary cast in [this PR](https://github.com/googleapis/gcs-resumable-upload/pull/220), from a user's point-of-view it would likely be expected that this value is a number.

### PR DESCRIPTION
**Pull request by praveenqlogic01**
Fixes #221 (it's a good idea to open an issue first for discussion)

- [ ] Tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -546,6 +546,9 @@ export class Upload extends Pumpify {
     reqOpts.validateStatus = () => true;
 
     const res = await this.authClient.request(reqOpts);
+    if (res && res.data) {
+      res.data.size = Number(res.data.size);
```
[the remark this answers is not in the document]
Comment (praveenqlogic01) [reply src/index.ts]: Done!

File: src/index.ts [hunk 2]
```diff
@@ -381,7 +381,9 @@ export class Upload extends Pumpify {
         this.destroy(new Error('Upload failed'));
         return;
       }
-
+      if (resp && resp.data) {
+        resp.data.size = Number(resp.data.size);
```
Comment (JustinBeckwith) [inline src/index.ts]: Generally I don't go too crazy here, but isn't this technically a breaking change?  @bcoe trust whatever you decide :)

File: test/test.ts [hunk 3]
```diff
@@ -545,6 +545,22 @@ describe('gcs-resumable-upload', () => {
       up.emit('response', RESP);
     });
 
+    it('should return response data size in number', done => {
```
Comment (bcoe) [inline test/test.ts]: mind changing to:

> should return response data size as number.

File: src/index.ts (hunk 2 above)
Comment (bcoe) [reply src/index.ts]: I think I'm okay with this as a patch, because anyone consuming the library is most likely calling:

`Number(resp.data.size)`

Which will continue to work with `size` already being converted to a number `Number(10) === 10`.

At the same time, I think this makes upstream code safer for folks who forget to convert the value.
